= findicon(1)
Lenik <iconlibutils@bodz.net>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: iconlibutils
:man-linkstyle: blue R <>
:nofooter:

== Name

findicon - Dateien an die Standardausgabe anhaengen

== Synopsis

*findicon* [_OPTION_]... [_FILE_]...

== Description

Jede _FILE_ der Reihe nach auf die Standardausgabe kopieren.
Ist _FILE_ ein einzelner Bindestrich (*-*), an dieser Stelle die
Standardeingabe lesen.
Wird keine _FILE_ angegeben, die Standardeingabe einmal lesen.

*findicon* ist im Geiste aehnlich wie *cat*(1): es schreibt die Verkettung der
Eingaben auf die Standardausgabe.

== Options

*-v, --verbose*::
  Jeden Dateinamen (oder ``standard input`` fuer *-*) vor dem Kopieren dieser
  Eingabe auf die Standardfehlerausgabe schreiben.
  Wiederholen fuer ausfuehrlichere Protokollierung.

*-q, --quiet*::
  Meldungen unterdruecken, die *--verbose* ausgeben wuerde.
  Wenn sowohl *--verbose* als auch *--quiet* angegeben sind, gewinnt
  *--quiet*.

*-h, --help*::
  Eine Nutzungsuebersicht ausgeben und erfolgreich beenden.

*--version*::
  Version und Lizenzinformationen ausgeben und erfolgreich beenden.

== Exit status

*0*::
  Erfolg.

*1*::
  Ein Fehler ist aufgetreten (ungueltige Optionen, unlesbare Datei oder
  E/A-Fehler).

== Author

Written by {project-author} <{project-email}>.

== Copyright

Copyright (C) {project-year}.
License AGPL-3.0-or-later.
Dies ist freie Software: Sie duerfen sie aendern und unter den Bedingungen der
GNU Affero General Public License weitergeben.
Es besteht KEINE GEWAEHRLEISTUNG, soweit gesetzlich zulaessig.
Siehe die Datei LICENSE in der Quellverteilung fuer den vollstaendigen
Lizenztext, einschliesslich ergaenzender Bedingungen, dass dieses Projekt
KI-Ausbeutung und KI-Hegemonie ablehnt sowie gedankenlose MIT-artige und
politisch naive BSD-artige Lizenzierung zurueckweist.
